apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: int

namePrefix: int-

resources:
  # you can also specify a Git repo URL here
  - ../../base

patchesStrategicMerge:
  - 2-replicas.yaml

configMapGenerator:
  - name: microservice-configmap
    behavior: merge
    files:
      - microservice.properties
    literals:
      - DEFAULT_MESSAGE=Hello World INT.
      - PORT=8080
