apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: productive-cloud-native-devex
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: lreimer/productive-cloud-native-devex
      # to build image with Jib
      #jib: {}

      # to build image with Buildpacks.io
      # buildpacks:
      #  builder: "gcr.io/buildpacks/builder:v1"
  local:
    useDockerCLI: false
    useBuildkit: true
test:
  - image: lreimer/productive-cloud-native-devex
    structureTests:
      - src/test/structure/war_exists_test.yaml
deploy:
  kubectl:
    manifests:
     - src/main/kubernetes/microservice.yaml
     - src/main/kubernetes/database.yaml
portForward:
  - resourceType: service
    resourceName: productive-cloud-native-devex
    namespace: default
    port: 8080
    localPort: 18080
profiles:
  - name: development
    activation:
      - kubeContext: docker-desktop
#    deploy:
#      kustomize:
#        path: "src/main/kubernetes/kustomize/overlays/dev"
#  - name: integration
#    activation:
#      - env: ENVIRONMENT=INT
#    deploy:
#      kustomize:
#        path: "src/main/kubernetes/kustomize/overlays/int"
#    portForward:
#      - resourceType: service
#        resourceName: int-productive-cloud-native-devex-v1
#        namespace: default
#        port: 8080
#        localPort: 18080
#  - name: production
#    activation:
#      - env: ENVIRONMENT=PROD
#    deploy:
#      kustomize:
#        path: "src/main/kubernetes/kustomize/overlays/prod"
