apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: prod

namePrefix: prod-

bases:
  # you can also specify a Git repo URL here
  - ../../base

patchesStrategicMerge:
  - 4-replicas.yaml
  - probes.yaml
  - loadbalancer.yaml

configMapGenerator:
  - name: microservice-configmap
    behavior: merge
    files:
      - microservice.properties
    literals:
      - DEFAULT_MESSAGE=Hello World PROD.
      - PORT=8080
